language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
sudo: required
services:
  - rabbitmq
install:
  - make install
  - pip install codecov
script: make test
after_success:
  - make dist
  - codecov
